### ISSUE TITLE
`parseSignature` should throw an error

### ISSUE THREAD

**Issue by julien-devatom** [morpho-labs/safer#16]
## Description
[parseSignature](https://github.com/morpho-labs/safer/blob/main/script/ExecTransaction.s.sol#L62) is logging an error and returning without error data if the signature is malformated. 
It can lead to inconsistent signature or invalid processing after

## Suggestion
revert the script
```solidity
if (line.length != 132) {
    revert InvalidSignature();
}
```

**Comment by Rubilmax** [comment]
It seems to me that the claim is incorrect: `parseSignature` returns early everytime a signature is malformed. A signature is thus added to the list of signatures iff it passes the checks, so there's no way an inconsistent signature gets processed via the `signatures` array.

**Comment by julien-devatom** [comment]
Oh yes, makes sense. I think is more a philosophy: due to the criticality of the tool, a malformed signature in a list of signatures that should all be valid is an error imo. So throwing an error in case of something weird is better imo, 

What do you think?

**Comment by Rubilmax** [comment]
This is definitely about philosophy of script behavior. I am ambivalent, as I see advantages in both solutions. Let's just revert, because at worst it requires a human to fix it (whereas unexpected behaviors could arise with a malformed signature).
