### ISSUE TITLE
Follow Safe signature framework

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-labs/safer#2]
https://docs.safe.global/learn/safe-core/safe-core-protocol/signatures

> The constant parts need to be sorted so that the recovered signers are sorted ascending (natural order) by address (not checksummed).

- [x] Signatures must be sorted by ascending signers
- [ ] Data must be appended at the end as well as the length

**Comment by Rubilmax** [comment]
What do you mean by "Data must be appended at the end as well as the length"?
